[versions]
agp = "8.13.0"
kotlin = "2.0.21"
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
playServicesWearable = "19.0.0"
composeBom = "2025.10.00"
composeMaterial = "1.5.3"
composeFoundation = "1.5.3"
wearToolingPreview = "1.0.0"
activityCompose = "1.11.0"
coreSplashscreen = "1.0.1"
composeLifecycle = '2.9.4'
playServicesCoroutines = "1.10.2"
wearInteraction = '1.1.0'
gson = "2.13.2"
utility = "1.2.3"
utilcode = "1.30.7"
eventbus = "3.3.1"
composeMaterial3 = "1.4.0"
rxjava2Android = "2.1.1"
rxjava2Java = "2.2.21"
rxjava2Kotlin = "2.4.0"
navigationCompose = "2.9.5"
wearPhoneInteractions = "1.1.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "composeMaterial" }
androidx-compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "composeFoundation" }
androidx-wear-tooling-preview = { group = "androidx.wear", name = "wear-tooling-preview", version.ref = "wearToolingPreview" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
compose-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeLifecycle" }
play-services-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "playServicesCoroutines" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
utility = { group = "com.github.phongnx", name = "Utility", version.ref = "utility" }
utilcode = { group = "com.blankj", name = "utilcode", version.ref = "utilcode" }
eventbus = { group = "org.greenrobot", name = "eventbus", version.ref = "eventbus" }
wear-interactions = { group = "androidx.wear", name = "wear-remote-interactions", version.ref = "wearInteraction" }
rxjava2-rxandroid = { group = "io.reactivex.rxjava2", name = "rxandroid", version.ref = "rxjava2Android" }
rxjava2-rxjava = { group = "io.reactivex.rxjava2", name = "rxjava", version.ref = "rxjava2Java" }
rxjava2-rxkotlin = { group = "io.reactivex.rxjava2", name = "rxkotlin", version.ref = "rxjava2Kotlin" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-wear-phone-interactions = { group = "androidx.wear", name = "wear-phone-interactions", version.ref = "wearPhoneInteractions" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

